/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package client;

import java.rmi.RemoteException;

/**
 *
 * @author jaanle
 */
public class MainWindow extends javax.swing.JFrame {

    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form MainWindow
     */
    public MainWindow() {
        //liitet‰‰n ProcessClientImplementation k‰yttˆliittym‰‰n
    	try {
			pci = new ProcessClientImplementation();
		} catch (RemoteException e) {
			e.printStackTrace();
		}
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        siloPanel = new javax.swing.JPanel();
        silo1Label = new javax.swing.JLabel();
        reserveSilo1 = new javax.swing.JToggleButton();
        silo1Status = new javax.swing.JLabel();
        silo2Label = new javax.swing.JLabel();
        silo2Status = new javax.swing.JLabel();
        reserveSilo2 = new javax.swing.JToggleButton();
        silo3Label = new javax.swing.JLabel();
        silo3Status = new javax.swing.JLabel();
        reserveSilo3 = new javax.swing.JToggleButton();
        silo4Label = new javax.swing.JLabel();
        silo4Status = new javax.swing.JLabel();
        reserveSilo4 = new javax.swing.JToggleButton();
        loginPanel = new javax.swing.JPanel();
        userNameLabel = new javax.swing.JLabel();
        userName = new javax.swing.JTextField();
        signIn = new javax.swing.JToggleButton();
        tankPanel = new javax.swing.JPanel();
        tank1Label = new javax.swing.JLabel();
        tank1Status = new javax.swing.JLabel();
        reserveTank1 = new javax.swing.JToggleButton();
        tank2Label = new javax.swing.JLabel();
        tank2Status = new javax.swing.JLabel();
        reserveTank2 = new javax.swing.JToggleButton();
        tank3Label = new javax.swing.JLabel();
        tank3Status = new javax.swing.JLabel();
        reserveTank3 = new javax.swing.JToggleButton();
        tank4Label = new javax.swing.JLabel();
        tank4Status = new javax.swing.JLabel();
        reserveTank4 = new javax.swing.JToggleButton();
        tank5Label = new javax.swing.JLabel();
        tank5Status = new javax.swing.JLabel();
        reserveTank5 = new javax.swing.JToggleButton();
        tank6Label = new javax.swing.JLabel();
        tank6Status = new javax.swing.JLabel();
        reserveTank6 = new javax.swing.JToggleButton();
        tank7Label = new javax.swing.JLabel();
        tank7Status = new javax.swing.JLabel();
        reserveTank7 = new javax.swing.JToggleButton();
        tank8Label = new javax.swing.JLabel();
        tank8Status = new javax.swing.JLabel();
        reserveTank8 = new javax.swing.JToggleButton();
        tank9Label = new javax.swing.JLabel();
        tank9Status = new javax.swing.JLabel();
        reserveTank9 = new javax.swing.JToggleButton();
        tank10Label = new javax.swing.JLabel();
        tank10Status = new javax.swing.JLabel();
        reserveTank10 = new javax.swing.JToggleButton();
        procPanel = new javax.swing.JPanel();
        proc1Status = new javax.swing.JLabel();
        proc1Label = new javax.swing.JLabel();
        startProc1 = new javax.swing.JToggleButton();
        proc2Label = new javax.swing.JLabel();
        reserveProc1 = new javax.swing.JToggleButton();
        reserveProc2 = new javax.swing.JToggleButton();
        startProc2 = new javax.swing.JToggleButton();
        proc2Status = new javax.swing.JLabel();
        proc3Status = new javax.swing.JLabel();
        startProc3 = new javax.swing.JToggleButton();
        reserveProc3 = new javax.swing.JToggleButton();
        proc3Label = new javax.swing.JLabel();
        proc3User = new javax.swing.JLabel();
        proc2User = new javax.swing.JLabel();
        proc1User = new javax.swing.JLabel();
        siloLoadPanel = new javax.swing.JPanel();
        siloLoadLabel = new javax.swing.JLabel();
        startSiloLoad = new javax.swing.JToggleButton();
        siloLoadConvStatus = new javax.swing.JLabel();
        pumpPanel = new javax.swing.JPanel();
        pump1Status = new javax.swing.JLabel();
        pump1Label = new javax.swing.JLabel();
        startPump1 = new javax.swing.JToggleButton();
        pump2Label = new javax.swing.JLabel();
        pump2Status = new javax.swing.JLabel();
        startPump2 = new javax.swing.JToggleButton();
        bpumpPanel = new javax.swing.JPanel();
        bpump1Label = new javax.swing.JLabel();
        bpump1Status = new javax.swing.JLabel();
        startBpump1 = new javax.swing.JToggleButton();
        bpump2Label = new javax.swing.JLabel();
        bpump2Status = new javax.swing.JLabel();
        startBpump2 = new javax.swing.JToggleButton();
        procLoadPanel = new javax.swing.JPanel();
        procLoadLabel1 = new javax.swing.JLabel();
        startProcLoad1 = new javax.swing.JToggleButton();
        ProcLoadConvStatus1 = new javax.swing.JLabel();
        startProcLoad2 = new javax.swing.JToggleButton();
        procLoadConvStatus2 = new javax.swing.JLabel();
        procLoadLabel2 = new javax.swing.JLabel();
        procLoadAmount1 = new javax.swing.JTextField();
        procLoadAmount2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        siloPanel.setBackground(new java.awt.Color(204, 204, 204));

        silo1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silo.jpg"))); // NOI18N
        silo1Label.setText("Silo 1");
        silo1Label.setFocusable(false);
        silo1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        silo1Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        reserveSilo1.setText("Reserve");
        reserveSilo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSilo1ActionPerformed(evt);
            }
        });

        silo1Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo1Status.setText("0");
        silo1Status.setMaximumSize(new java.awt.Dimension(100, 200));
        silo1Status.setMinimumSize(new java.awt.Dimension(100, 20));
        silo1Status.setPreferredSize(new java.awt.Dimension(100, 20));

        silo2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silo.jpg"))); // NOI18N
        silo2Label.setText("Silo 2");
        silo2Label.setFocusable(false);
        silo2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        silo2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        silo2Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo2Status.setText("0");
        silo2Status.setMaximumSize(new java.awt.Dimension(100, 200));
        silo2Status.setMinimumSize(new java.awt.Dimension(100, 20));
        silo2Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveSilo2.setText("Reserve");
        reserveSilo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSilo2ActionPerformed(evt);
            }
        });

        silo3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silo.jpg"))); // NOI18N
        silo3Label.setText("Silo 3");
        silo3Label.setFocusable(false);
        silo3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        silo3Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        silo3Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo3Status.setText("0");
        silo3Status.setMaximumSize(new java.awt.Dimension(100, 200));
        silo3Status.setMinimumSize(new java.awt.Dimension(100, 20));
        silo3Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveSilo3.setText("Reserve");
        reserveSilo3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSilo3ActionPerformed(evt);
            }
        });

        silo4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/silo.jpg"))); // NOI18N
        silo4Label.setText("Silo 4");
        silo4Label.setFocusable(false);
        silo4Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        silo4Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        silo4Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        silo4Status.setText("0");
        silo4Status.setMaximumSize(new java.awt.Dimension(100, 200));
        silo4Status.setMinimumSize(new java.awt.Dimension(100, 20));
        silo4Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveSilo4.setText("Reserve");
        reserveSilo4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveSilo4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout siloPanelLayout = new javax.swing.GroupLayout(siloPanel);
        siloPanel.setLayout(siloPanelLayout);
        siloPanelLayout.setHorizontalGroup(
            siloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siloPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(siloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(silo1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveSilo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silo1Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silo2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silo2Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveSilo2)
                    .addComponent(silo3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silo3Status, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveSilo3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silo4Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(silo4Status, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(reserveSilo4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        siloPanelLayout.setVerticalGroup(
            siloPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siloPanelLayout.createSequentialGroup()
                .addComponent(silo1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silo1Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveSilo1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silo2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(silo2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveSilo2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silo3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silo3Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addComponent(reserveSilo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silo4Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(silo4Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveSilo4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        userNameLabel.setText("Username");

        userName.setToolTipText("");

        signIn.setText("Log in");
        signIn.setToolTipText("");
        signIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loginPanelLayout = new javax.swing.GroupLayout(loginPanel);
        loginPanel.setLayout(loginPanelLayout);
        loginPanelLayout.setHorizontalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userNameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(signIn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        loginPanelLayout.setVerticalGroup(
            loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loginPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(userNameLabel)
                    .addGroup(loginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(userName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(signIn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tankPanel.setBackground(new java.awt.Color(204, 204, 204));

        tank1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank1Label.setText("Tank 1");
        tank1Label.setFocusable(false);
        tank1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank1Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank1Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank1Status.setText("0");
        tank1Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank1Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank1Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank1.setText("Reserve");
        reserveTank1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank1ActionPerformed(evt);
            }
        });

        tank2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank2Label.setText("Tank 2");
        tank2Label.setFocusable(false);
        tank2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank2Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank2Status.setText("0");
        tank2Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank2Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank2Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank2.setText("Reserve");
        reserveTank2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank2ActionPerformed(evt);
            }
        });

        tank3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank3Label.setText("Tank 3");
        tank3Label.setFocusable(false);
        tank3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank3Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank3Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank3Status.setText("0");
        tank3Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank3Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank3Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank3.setText("Reserve");
        reserveTank3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank3ActionPerformed(evt);
            }
        });

        tank4Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank4Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank4Label.setText("Tank 4");
        tank4Label.setFocusable(false);
        tank4Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank4Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank4Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank4Status.setText("0");
        tank4Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank4Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank4Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank4.setText("Reserve");
        reserveTank4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank4ActionPerformed(evt);
            }
        });

        tank5Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank5Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank5Label.setText("Tank 5");
        tank5Label.setFocusable(false);
        tank5Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank5Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank5Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank5Status.setText("0");
        tank5Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank5Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank5Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank5.setText("Reserve");
        reserveTank5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank5ActionPerformed(evt);
            }
        });

        tank6Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank6Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank6Label.setText("Tank 6");
        tank6Label.setFocusable(false);
        tank6Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank6Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank6Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank6Status.setText("0");
        tank6Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank6Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank6Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank6.setText("Reserve");
        reserveTank6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank6ActionPerformed(evt);
            }
        });

        tank7Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank7Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank7Label.setText("Tank 7");
        tank7Label.setFocusable(false);
        tank7Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank7Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank7Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank7Status.setText("0");
        tank7Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank7Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank7Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank7.setText("Reserve");
        reserveTank7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank7ActionPerformed(evt);
            }
        });

        tank8Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank8Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank8Label.setText("Tank 8");
        tank8Label.setFocusable(false);
        tank8Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank8Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank8Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank8Status.setText("0");
        tank8Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank8Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank8Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank8.setText("Reserve");
        reserveTank8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank8ActionPerformed(evt);
            }
        });

        tank9Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank9Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank9Label.setText("Tank 9");
        tank9Label.setFocusable(false);
        tank9Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank9Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank9Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank9Status.setText("0");
        tank9Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank9Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank9Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank9.setText("Reserve");
        reserveTank9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank9ActionPerformed(evt);
            }
        });

        tank10Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank10Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tank.jpg"))); // NOI18N
        tank10Label.setText("Tank 10");
        tank10Label.setFocusable(false);
        tank10Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tank10Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        tank10Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tank10Status.setText("0");
        tank10Status.setMaximumSize(new java.awt.Dimension(100, 200));
        tank10Status.setMinimumSize(new java.awt.Dimension(100, 20));
        tank10Status.setPreferredSize(new java.awt.Dimension(100, 20));

        reserveTank10.setText("Reserve");
        reserveTank10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveTank10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout tankPanelLayout = new javax.swing.GroupLayout(tankPanel);
        tankPanel.setLayout(tankPanelLayout);
        tankPanelLayout.setHorizontalGroup(
            tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tankPanelLayout.createSequentialGroup()
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tank1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tank1Status, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(reserveTank1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tank2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tank2Status, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                    .addComponent(reserveTank2)
                    .addComponent(tank3Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank3Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank3)
                    .addComponent(tank4Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank4Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank4)
                    .addComponent(tank5Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank5Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank5))
                .addGap(10, 10, 10)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(tank6Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank6Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank6)
                    .addComponent(tank7Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank7Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank7)
                    .addComponent(tank8Label)
                    .addComponent(tank8Status, javax.swing.GroupLayout.PREFERRED_SIZE, 77, Short.MAX_VALUE)
                    .addComponent(reserveTank8)
                    .addComponent(tank9Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank9Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank9)
                    .addComponent(tank10Label, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank10Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(reserveTank10)))
        );
        tankPanelLayout.setVerticalGroup(
            tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(tankPanelLayout.createSequentialGroup()
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tank1Label)
                    .addComponent(tank6Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tank1Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank6Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveTank1)
                    .addComponent(reserveTank6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tank2Label)
                    .addComponent(tank7Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, tankPanelLayout.createSequentialGroup()
                        .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tank2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tank7Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(reserveTank2)
                            .addComponent(reserveTank7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tank3Label))
                    .addComponent(tank8Label, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tank3Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank8Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveTank3)
                    .addComponent(reserveTank8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tank4Label)
                    .addComponent(tank9Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tank4Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank9Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveTank4)
                    .addComponent(reserveTank9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tank10Label)
                    .addComponent(tank5Label))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tank10Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tank5Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(tankPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reserveTank10)
                    .addComponent(reserveTank5)))
        );

        procPanel.setBackground(new java.awt.Color(204, 204, 204));

        proc1Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc1Status.setText("Running");
        proc1Status.setMaximumSize(new java.awt.Dimension(100, 200));
        proc1Status.setMinimumSize(new java.awt.Dimension(100, 20));
        proc1Status.setPreferredSize(new java.awt.Dimension(100, 20));

        proc1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/processor.jpg"))); // NOI18N
        proc1Label.setText("Processor 1");
        proc1Label.setFocusable(false);
        proc1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        proc1Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        startProc1.setText("Start");
        startProc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProc1ActionPerformed(evt);
            }
        });

        proc2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/processor.jpg"))); // NOI18N
        proc2Label.setText("Processor 2");
        proc2Label.setFocusable(false);
        proc2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        proc2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        reserveProc1.setText("Reserve");
        reserveProc1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveProc1ActionPerformed(evt);
            }
        });

        reserveProc2.setText("Reserve");
        reserveProc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveProc2ActionPerformed(evt);
            }
        });

        startProc2.setText("Start");
        startProc2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProc2ActionPerformed(evt);
            }
        });

        proc2Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc2Status.setText("Running");
        proc2Status.setMaximumSize(new java.awt.Dimension(100, 200));
        proc2Status.setMinimumSize(new java.awt.Dimension(100, 20));
        proc2Status.setPreferredSize(new java.awt.Dimension(100, 20));

        proc3Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc3Status.setText("Running");
        proc3Status.setMaximumSize(new java.awt.Dimension(100, 200));
        proc3Status.setMinimumSize(new java.awt.Dimension(100, 20));
        proc3Status.setPreferredSize(new java.awt.Dimension(100, 20));

        startProc3.setText("Start");
        startProc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProc3ActionPerformed(evt);
            }
        });

        reserveProc3.setText("Reserve");
        reserveProc3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reserveProc3ActionPerformed(evt);
            }
        });

        proc3Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc3Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/processor.jpg"))); // NOI18N
        proc3Label.setText("Processor 3");
        proc3Label.setFocusable(false);
        proc3Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        proc3Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        proc3User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc3User.setText("User");

        proc2User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc2User.setText("User");

        proc1User.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        proc1User.setText("User");

        javax.swing.GroupLayout procPanelLayout = new javax.swing.GroupLayout(procPanel);
        procPanel.setLayout(procPanelLayout);
        procPanelLayout.setHorizontalGroup(
            procPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(procPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(proc1Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(proc1Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startProc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proc2Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reserveProc1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reserveProc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(startProc2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proc2Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(proc3Status, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startProc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(reserveProc3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proc3Label, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proc3User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proc2User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(proc1User, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        procPanelLayout.setVerticalGroup(
            procPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, procPanelLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(proc1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proc1User, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proc1Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveProc1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startProc1)
                .addGap(18, 18, 18)
                .addComponent(proc2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proc2User, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proc2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveProc2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startProc2)
                .addGap(29, 29, 29)
                .addComponent(proc3Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proc3User, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(proc3Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(reserveProc3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startProc3)
                .addContainerGap())
        );

        siloLoadLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siloLoadLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conveyor.jpg"))); // NOI18N
        siloLoadLabel.setText("Silo loading");
        siloLoadLabel.setFocusable(false);
        siloLoadLabel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        siloLoadLabel.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        startSiloLoad.setText("Start");
        startSiloLoad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startSiloLoadActionPerformed(evt);
            }
        });

        siloLoadConvStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        siloLoadConvStatus.setText("Not Running");
        siloLoadConvStatus.setMaximumSize(new java.awt.Dimension(100, 200));
        siloLoadConvStatus.setMinimumSize(new java.awt.Dimension(100, 20));
        siloLoadConvStatus.setPreferredSize(new java.awt.Dimension(100, 20));

        javax.swing.GroupLayout siloLoadPanelLayout = new javax.swing.GroupLayout(siloLoadPanel);
        siloLoadPanel.setLayout(siloLoadPanelLayout);
        siloLoadPanelLayout.setHorizontalGroup(
            siloLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(siloLoadPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(siloLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(siloLoadLabel)
                    .addComponent(startSiloLoad)
                    .addComponent(siloLoadConvStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(11, Short.MAX_VALUE))
        );
        siloLoadPanelLayout.setVerticalGroup(
            siloLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, siloLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(siloLoadLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(siloLoadConvStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startSiloLoad)
                .addContainerGap())
        );

        siloLoadConvStatus.getAccessibleContext().setAccessibleName("SiloLoadConvStatus");

        pump1Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pump1Status.setText("Running");
        pump1Status.setMaximumSize(new java.awt.Dimension(100, 200));
        pump1Status.setMinimumSize(new java.awt.Dimension(100, 20));
        pump1Status.setPreferredSize(new java.awt.Dimension(100, 20));

        pump1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pump1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pump.jpg"))); // NOI18N
        pump1Label.setText("Pump 1");
        pump1Label.setFocusable(false);
        pump1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pump1Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        startPump1.setText("Start");
        startPump1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPump1ActionPerformed(evt);
            }
        });

        pump2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pump2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pump.jpg"))); // NOI18N
        pump2Label.setText("Pump 2");
        pump2Label.setFocusable(false);
        pump2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pump2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        pump2Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        pump2Status.setText("Running");
        pump2Status.setMaximumSize(new java.awt.Dimension(100, 200));
        pump2Status.setMinimumSize(new java.awt.Dimension(100, 20));
        pump2Status.setPreferredSize(new java.awt.Dimension(100, 20));

        startPump2.setText("Start");
        startPump2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startPump2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pumpPanelLayout = new javax.swing.GroupLayout(pumpPanel);
        pumpPanel.setLayout(pumpPanelLayout);
        pumpPanelLayout.setHorizontalGroup(
            pumpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pumpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(pump1Status, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pump1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startPump1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pump2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(pump2Status, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startPump2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pumpPanelLayout.setVerticalGroup(
            pumpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pumpPanelLayout.createSequentialGroup()
                .addComponent(pump1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pump1Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startPump1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pump2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pump2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startPump2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bpump1Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpump1Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pump.jpg"))); // NOI18N
        bpump1Label.setText("Bottle pump 1");
        bpump1Label.setFocusable(false);
        bpump1Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bpump1Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        bpump1Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpump1Status.setText("Running");
        bpump1Status.setMaximumSize(new java.awt.Dimension(100, 200));
        bpump1Status.setMinimumSize(new java.awt.Dimension(100, 20));
        bpump1Status.setPreferredSize(new java.awt.Dimension(100, 20));

        startBpump1.setText("Start");
        startBpump1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBpump1ActionPerformed(evt);
            }
        });

        bpump2Label.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpump2Label.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/pump.jpg"))); // NOI18N
        bpump2Label.setText("Bottle pump 2");
        bpump2Label.setFocusable(false);
        bpump2Label.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        bpump2Label.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        bpump2Status.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        bpump2Status.setText("Running");
        bpump2Status.setMaximumSize(new java.awt.Dimension(100, 200));
        bpump2Status.setMinimumSize(new java.awt.Dimension(100, 20));
        bpump2Status.setPreferredSize(new java.awt.Dimension(100, 20));

        startBpump2.setText("Start");
        startBpump2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startBpump2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bpumpPanelLayout = new javax.swing.GroupLayout(bpumpPanel);
        bpumpPanel.setLayout(bpumpPanelLayout);
        bpumpPanelLayout.setHorizontalGroup(
            bpumpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bpumpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                .addComponent(bpump1Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bpump1Status, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startBpump1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bpump2Label, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(bpump2Status, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(startBpump2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        bpumpPanelLayout.setVerticalGroup(
            bpumpPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bpumpPanelLayout.createSequentialGroup()
                .addComponent(bpump1Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpump1Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startBpump1)
                .addGap(18, 18, 18)
                .addComponent(bpump2Label)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bpump2Status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startBpump2))
        );

        procLoadLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procLoadLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conveyor.jpg"))); // NOI18N
        procLoadLabel1.setText("Processor loading");
        procLoadLabel1.setFocusable(false);
        procLoadLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        procLoadLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        startProcLoad1.setText("Start");
        startProcLoad1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProcLoad1ActionPerformed(evt);
            }
        });

        ProcLoadConvStatus1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ProcLoadConvStatus1.setText("Running");
        ProcLoadConvStatus1.setMaximumSize(new java.awt.Dimension(100, 200));
        ProcLoadConvStatus1.setMinimumSize(new java.awt.Dimension(100, 20));
        ProcLoadConvStatus1.setPreferredSize(new java.awt.Dimension(100, 20));

        startProcLoad2.setText("Start");
        startProcLoad2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startProcLoad2ActionPerformed(evt);
            }
        });

        procLoadConvStatus2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procLoadConvStatus2.setText("Running");
        procLoadConvStatus2.setMaximumSize(new java.awt.Dimension(100, 200));
        procLoadConvStatus2.setMinimumSize(new java.awt.Dimension(100, 20));
        procLoadConvStatus2.setPreferredSize(new java.awt.Dimension(100, 20));

        procLoadLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        procLoadLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conveyor.jpg"))); // NOI18N
        procLoadLabel2.setText("Processor loading");
        procLoadLabel2.setFocusable(false);
        procLoadLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        procLoadLabel2.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        procLoadAmount1.setPreferredSize(new java.awt.Dimension(65, 20));
        procLoadAmount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procLoadAmount1ActionPerformed(evt);
            }
        });

        procLoadAmount2.setPreferredSize(new java.awt.Dimension(65, 20));
        procLoadAmount2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procLoadAmount2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout procLoadPanelLayout = new javax.swing.GroupLayout(procLoadPanel);
        procLoadPanel.setLayout(procLoadPanelLayout);
        procLoadPanelLayout.setHorizontalGroup(
            procLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(procLoadPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(procLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(procLoadLabel1)
                    .addComponent(procLoadAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProcLoadConvStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startProcLoad1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procLoadLabel2)
                    .addComponent(procLoadAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(procLoadConvStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(startProcLoad2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        procLoadPanelLayout.setVerticalGroup(
            procLoadPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(procLoadPanelLayout.createSequentialGroup()
                .addComponent(procLoadLabel1)
                .addGap(7, 7, 7)
                .addComponent(procLoadAmount1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ProcLoadConvStatus1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startProcLoad1)
                .addGap(32, 32, 32)
                .addComponent(procLoadLabel2)
                .addGap(8, 8, 8)
                .addComponent(procLoadAmount2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(procLoadConvStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(startProcLoad2)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(siloLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(siloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(procLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)))
                .addComponent(procPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addComponent(pumpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(tankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bpumpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(77, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(loginPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(siloPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(siloLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(procLoadPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(pumpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tankPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(procPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(bpumpPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void startSiloLoadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startSiloLoadActionPerformed
        // TODO Mit‰ tehd‰‰n, kun siilojen t‰ytˆn ruuvikuljetin k‰ynnistet‰‰n?
    	siloLoadLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/conveyorinuse.jpg")));
        siloLoadConvStatus.setText("Running");

    }//GEN-LAST:event_startSiloLoadActionPerformed

    private void signInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signInActionPerformed
        // TODO Mit‰ tehd‰‰n kun k‰ytt‰j‰ kirjautuu
    	pci.inform();
    }//GEN-LAST:event_signInActionPerformed

    private void startProcLoad1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProcLoad1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keittimen t‰ytˆn ruuvikuljetin 1 k‰ynnistet‰‰n
    }//GEN-LAST:event_startProcLoad1ActionPerformed

    private void startProcLoad2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProcLoad2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keittimen t‰ytˆn ruuvikuljetin 1 k‰ynnistet‰‰n
    }//GEN-LAST:event_startProcLoad2ActionPerformed

    private void reserveSilo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSilo1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun siilo1 varataan?
    }//GEN-LAST:event_reserveSilo1ActionPerformed

    private void reserveSilo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSilo2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun siilo2 varataan?
    }//GEN-LAST:event_reserveSilo2ActionPerformed

    private void reserveSilo3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSilo3ActionPerformed
        // TODO Mit‰ tehd‰‰n kun siilo3 varataan?
    }//GEN-LAST:event_reserveSilo3ActionPerformed

    private void reserveSilo4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveSilo4ActionPerformed
        // TODO Mit‰ tehd‰‰n kun siilo4 varataan?
    }//GEN-LAST:event_reserveSilo4ActionPerformed

    private void reserveProc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveProc1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keitin1 varataan?
    }//GEN-LAST:event_reserveProc1ActionPerformed

    private void startProc1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProc1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keitin1 k‰ynnistet‰‰n?
    }//GEN-LAST:event_startProc1ActionPerformed

    private void reserveProc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveProc2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keitin2 varataan?
    }//GEN-LAST:event_reserveProc2ActionPerformed

    private void startProc2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProc2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keitin2 k‰ynnistet‰‰n?
    }//GEN-LAST:event_startProc2ActionPerformed

    private void reserveProc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveProc3ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keitin3 varataan?
    }//GEN-LAST:event_reserveProc3ActionPerformed

    private void startProc3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startProc3ActionPerformed
        // TODO Mit‰ tehd‰‰n kun keitin3 k‰ynnistet‰‰n?
    }//GEN-LAST:event_startProc3ActionPerformed

    private void startPump1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPump1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun pumppu1 k‰ynnistet‰‰n?
    }//GEN-LAST:event_startPump1ActionPerformed

    private void startPump2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startPump2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun pumppu2 k‰ynnistet‰‰n?
    }//GEN-LAST:event_startPump2ActionPerformed

    private void startBpump1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBpump1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun pumppu1 pullotukseen k‰ynnistet‰‰n?
    }//GEN-LAST:event_startBpump1ActionPerformed

    private void startBpump2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startBpump2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun pumppu2 pullotukseen k‰ynnistet‰‰n?
    }//GEN-LAST:event_startBpump2ActionPerformed

    private void reserveTank1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank1ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ1 varataan?
    }//GEN-LAST:event_reserveTank1ActionPerformed

    private void reserveTank2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank2ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ2 varataan?
    }//GEN-LAST:event_reserveTank2ActionPerformed

    private void reserveTank3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank3ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ3 varataan?
    }//GEN-LAST:event_reserveTank3ActionPerformed

    private void reserveTank4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank4ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ4 varataan?
    }//GEN-LAST:event_reserveTank4ActionPerformed

    private void reserveTank5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank5ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ5 varataan?
    }//GEN-LAST:event_reserveTank5ActionPerformed

    private void reserveTank6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank6ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ6 varataan?
    }//GEN-LAST:event_reserveTank6ActionPerformed

    private void reserveTank7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank7ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ7 varataan?
    }//GEN-LAST:event_reserveTank7ActionPerformed

    private void reserveTank8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank8ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ8 varataan?
    }//GEN-LAST:event_reserveTank8ActionPerformed

    private void reserveTank9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank9ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ9 varataan?
    }//GEN-LAST:event_reserveTank9ActionPerformed

    private void reserveTank10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reserveTank10ActionPerformed
        // TODO Mit‰ tehd‰‰n kun s‰iliˆ10 varataan?
    }//GEN-LAST:event_reserveTank10ActionPerformed

    private void procLoadAmount2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procLoadAmount2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procLoadAmount2ActionPerformed

    private void procLoadAmount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procLoadAmount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_procLoadAmount1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String[] args){
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */

    	try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });

    }

    //K‰yttˆliittym‰‰n liittyv‰ asiakas
    private ProcessClientImplementation pci;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProcLoadConvStatus1;
    private javax.swing.JLabel bpump1Label;
    private javax.swing.JLabel bpump1Status;
    private javax.swing.JLabel bpump2Label;
    private javax.swing.JLabel bpump2Status;
    private javax.swing.JPanel bpumpPanel;
    private javax.swing.JPanel loginPanel;
    private javax.swing.JLabel proc1Label;
    private javax.swing.JLabel proc1Status;
    private javax.swing.JLabel proc1User;
    private javax.swing.JLabel proc2Label;
    private javax.swing.JLabel proc2Status;
    private javax.swing.JLabel proc2User;
    private javax.swing.JLabel proc3Label;
    private javax.swing.JLabel proc3Status;
    private javax.swing.JLabel proc3User;
    private javax.swing.JTextField procLoadAmount1;
    private javax.swing.JTextField procLoadAmount2;
    private javax.swing.JLabel procLoadConvStatus2;
    private javax.swing.JLabel procLoadLabel1;
    private javax.swing.JLabel procLoadLabel2;
    private javax.swing.JPanel procLoadPanel;
    private javax.swing.JPanel procPanel;
    private javax.swing.JLabel pump1Label;
    private javax.swing.JLabel pump1Status;
    private javax.swing.JLabel pump2Label;
    private javax.swing.JLabel pump2Status;
    private javax.swing.JPanel pumpPanel;
    private javax.swing.JToggleButton reserveProc1;
    private javax.swing.JToggleButton reserveProc2;
    private javax.swing.JToggleButton reserveProc3;
    private javax.swing.JToggleButton reserveSilo1;
    private javax.swing.JToggleButton reserveSilo2;
    private javax.swing.JToggleButton reserveSilo3;
    private javax.swing.JToggleButton reserveSilo4;
    private javax.swing.JToggleButton reserveTank1;
    private javax.swing.JToggleButton reserveTank10;
    private javax.swing.JToggleButton reserveTank2;
    private javax.swing.JToggleButton reserveTank3;
    private javax.swing.JToggleButton reserveTank4;
    private javax.swing.JToggleButton reserveTank5;
    private javax.swing.JToggleButton reserveTank6;
    private javax.swing.JToggleButton reserveTank7;
    private javax.swing.JToggleButton reserveTank8;
    private javax.swing.JToggleButton reserveTank9;
    private javax.swing.JToggleButton signIn;
    private javax.swing.JLabel silo1Label;
    private javax.swing.JLabel silo1Status;
    private javax.swing.JLabel silo2Label;
    private javax.swing.JLabel silo2Status;
    private javax.swing.JLabel silo3Label;
    private javax.swing.JLabel silo3Status;
    private javax.swing.JLabel silo4Label;
    private javax.swing.JLabel silo4Status;
    private javax.swing.JLabel siloLoadConvStatus;
    private javax.swing.JLabel siloLoadLabel;
    private javax.swing.JPanel siloLoadPanel;
    private javax.swing.JPanel siloPanel;
    private javax.swing.JToggleButton startBpump1;
    private javax.swing.JToggleButton startBpump2;
    private javax.swing.JToggleButton startProc1;
    private javax.swing.JToggleButton startProc2;
    private javax.swing.JToggleButton startProc3;
    private javax.swing.JToggleButton startProcLoad1;
    private javax.swing.JToggleButton startProcLoad2;
    private javax.swing.JToggleButton startPump1;
    private javax.swing.JToggleButton startPump2;
    private javax.swing.JToggleButton startSiloLoad;
    private javax.swing.JLabel tank10Label;
    private javax.swing.JLabel tank10Status;
    private javax.swing.JLabel tank1Label;
    private javax.swing.JLabel tank1Status;
    private javax.swing.JLabel tank2Label;
    private javax.swing.JLabel tank2Status;
    private javax.swing.JLabel tank3Label;
    private javax.swing.JLabel tank3Status;
    private javax.swing.JLabel tank4Label;
    private javax.swing.JLabel tank4Status;
    private javax.swing.JLabel tank5Label;
    private javax.swing.JLabel tank5Status;
    private javax.swing.JLabel tank6Label;
    private javax.swing.JLabel tank6Status;
    private javax.swing.JLabel tank7Label;
    private javax.swing.JLabel tank7Status;
    private javax.swing.JLabel tank8Label;
    private javax.swing.JLabel tank8Status;
    private javax.swing.JLabel tank9Label;
    private javax.swing.JLabel tank9Status;
    private javax.swing.JPanel tankPanel;
    private javax.swing.JTextField userName;
    private javax.swing.JLabel userNameLabel;
    // End of variables declaration//GEN-END:variables
}
